# Generated by Django 5.1.1 on 2024-09-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country_city", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="نام"),
                ),
                (
                    "family",
                    models.CharField(
                        max_length=100, null=True, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=20, null=True, verbose_name="نام پدر"),
                ),
                (
                    "unique_code",
                    models.CharField(
                        help_text="لطفا کد ملی یا اتباع را وراد نمایید",
                        max_length=30,
                        null=True,
                        verbose_name="کد ملی یا اتباع",
                    ),
                ),
                (
                    "happy_birthday",
                    models.DateTimeField(
                        help_text="در نظر داشته باشید افراد خارجی تاریخ تولد چطور ثبت شود",
                        null=True,
                        verbose_name="تاریخ تولد",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("---", "نامشخص"), ("man", "آقا"), ("female", "خانم")],
                        default="---",
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Profile/Picture/",
                        verbose_name="تصویر کاربری",
                    ),
                ),
                (
                    "additaion_address",
                    models.TextField(
                        blank=True, default="--", null=True, verbose_name="جزئیات آدرس"
                    ),
                ),
                (
                    "status_person",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school_student", "دانش آموز"),
                            ("uni_student", "دانشجو"),
                            ("interest", "علاقه مند"),
                        ],
                        default="interest",
                        max_length=40,
                        null=True,
                        verbose_name="وضعیت فرد مورد نظر",
                    ),
                ),
                (
                    "city",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="country_city.city",
                        verbose_name="نام شهر",
                    ),
                ),
                (
                    "country",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="country_city.country",
                        verbose_name="نام کشور",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرد مورد نظر",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "اطلاعات حساب کاربری",
                "db_table": "Profile_Information",
            },
        ),
    ]
