# Generated by Django 5.1.1 on 2024-09-05 19:45

import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته بندی"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="آدرس دسته بندی")),
            ],
            options={
                "verbose_name_plural": "دسته بندی های وبلاگ",
                "db_table": "Category_Blog",
            },
        ),
        migrations.CreateModel(
            name="Tags_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تگ")),
            ],
            options={
                "verbose_name_plural": "تگ های پست ها",
                "db_table": "Tags_Post",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summer_text",
                    ckeditor.fields.RichTextField(null=True, verbose_name="خلاصه متن"),
                ),
                (
                    "picture",
                    models.FileField(upload_to="blog/Post/", verbose_name="تصویر"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="عنوان پست")),
                ("slug", models.SlugField(verbose_name="آدرس اینترنتی")),
                (
                    "description1",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="توضیحات"),
                ),
                (
                    "description2",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "times",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, null=True, verbose_name="زمان ایجاد"
                    ),
                ),
                (
                    "time_to_read",
                    models.PositiveIntegerField(null=True, verbose_name="زمان  خواندن"),
                ),
                (
                    "author_idea",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="نظر نویسنده"
                    ),
                ),
                (
                    "banner1",
                    models.FileField(
                        null=True,
                        upload_to="Post/Banner/banner1",
                        verbose_name="بنر تبلیغاتی 1 ",
                    ),
                ),
                (
                    "banner2",
                    models.FileField(
                        null=True,
                        upload_to="Post/Banner/banner2",
                        verbose_name="بنر تبلیغاتی 2 ",
                    ),
                ),
                (
                    "banner3",
                    models.FileField(
                        null=True,
                        upload_to="Post/Banner/banner3",
                        verbose_name="بنر تبلیغاتی  3",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="blog.category_blog",
                        verbose_name="دسته بندی ",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="blog.tags_post", verbose_name="تگ ها"),
                ),
            ],
            options={
                "verbose_name_plural": "پست های وبلاگ",
                "db_table": "Post",
                "ordering": ["times"],
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام پاسخ دهنده"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="ایمیل پاسخ دهنده"),
                ),
                ("text", models.TextField(verbose_name="متن پاسخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_check", "بدون چک"),
                            ("checheck", "چک"),
                            ("pass", "تایید"),
                        ],
                        default="no_check",
                        max_length=20,
                        verbose_name="وضعیت بررسی کامنت",
                    ),
                ),
                (
                    "times",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, null=True, verbose_name=""
                    ),
                ),
                (
                    "post_selected",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                        verbose_name="پست انتخاب شده",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های وبلاگ",
                "db_table": "PostComment",
            },
        ),
    ]
