# Generated by Django 5.1.1 on 2024-09-05 19:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_goad",
                    models.CharField(
                        max_length=50, null=True, verbose_name="متن هدف در درباره ما"
                    ),
                ),
                (
                    "picture1",
                    models.FileField(null=True, upload_to="", verbose_name="تصویر 1 "),
                ),
                (
                    "picture2",
                    models.FileField(null=True, upload_to="", verbose_name="تصویر 2 "),
                ),
                (
                    "picture3",
                    models.FileField(null=True, upload_to="", verbose_name="تصویر 3 "),
                ),
                (
                    "picture4",
                    models.FileField(null=True, upload_to="", verbose_name="تصویر 4 "),
                ),
                ("title", models.CharField(max_length=100, verbose_name="درباره ما")),
                (
                    "picture",
                    models.FileField(
                        upload_to="AboutUs/", verbose_name="تصویر درباره ما"
                    ),
                ),
                (
                    "title_1",
                    models.CharField(
                        max_length=100, null=True, verbose_name="توضیحات 1 "
                    ),
                ),
                (
                    "text1",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 1"
                    ),
                ),
                (
                    "title_2",
                    models.CharField(
                        max_length=100, null=True, verbose_name="توضیحات 2 "
                    ),
                ),
                (
                    "text2",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 2"
                    ),
                ),
                (
                    "title_3",
                    models.CharField(
                        max_length=100, null=True, verbose_name="توضیحات 3 "
                    ),
                ),
                (
                    "text3",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 3 "
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "درباره ما",
                "db_table": "AboutUs",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "family",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "phone",
                    models.CharField(
                        max_length=11, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                ("text", models.TextField(verbose_name="متن")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre", "بدون بررسی"),
                            ("now", "در حال بررسی"),
                            ("end", "تمام شده"),
                        ],
                        default="pre",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ارتباط با ما",
                "db_table": "ContactUs",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان سوال")),
                ("text", ckeditor.fields.RichTextField(verbose_name="متن")),
            ],
            options={
                "verbose_name_plural": "سوالات پر تکرار ",
                "db_table": "FAQ",
            },
        ),
        migrations.CreateModel(
            name="MainSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تصویر")),
                (
                    "text",
                    models.CharField(
                        max_length=100, null=True, verbose_name="متن صفحه اول"
                    ),
                ),
                (
                    "picture",
                    models.FileField(upload_to="MainSlider/", verbose_name="تصویر"),
                ),
            ],
            options={
                "verbose_name_plural": "تصاویر اسلایدر ابتدایی",
                "db_table": "MainSlider",
            },
        ),
        migrations.CreateModel(
            name="MyTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        upload_to="MyTeams/Picture/", verbose_name="تصویر هم تیمی"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=100, null=True, verbose_name="سمت در شرکت"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
            ],
            options={
                "verbose_name_plural": "هم تیمی ها",
                "db_table": "MyTeams",
            },
        ),
        migrations.CreateModel(
            name="Supporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام حامی ما")),
                (
                    "picture",
                    models.FileField(upload_to="Supporter/", verbose_name="لوگو"),
                ),
            ],
            options={
                "verbose_name_plural": "همراهان ما",
                "db_table": "Supporter",
            },
        ),
        migrations.CreateModel(
            name="Year_Student_Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=5, verbose_name="سال")),
                (
                    "text",
                    models.CharField(
                        max_length=50, null=True, verbose_name="متن ورودی"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تعداد دانش آموزان و کارمندان در سال ",
                "db_table": "Year_Student_Stuff",
            },
        ),
    ]
